run:
  timeout: 7m

linters:
  enable:
    - contextcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert

linters-settings:
  goimports:
    local-prefixes: github.com/NVIDIA/k8s-kata-manager
  gosec:
    excludes:
      - G204