apiVersion: apps/v1
kind: DaemonSet
metadata:
  generation: 1
  name: k8s-kata-manager
spec:
  selector:
    matchLabels:
      name: kata-manager
  template:
    metadata:
      labels:
        name: kata-manager
    spec:
      serviceAccountName: kata-manager-sa
      hostPID: true
      imagePullSecrets: {}
      containers:
      - command:
          - k8s-kata-manager
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: nvcr.io/nvidia/cloud-native/k8s-kata-manager:v0.2.2
        imagePullPolicy: Always
        name: k8s-kata-manager
        resources: {}
        securityContext:
          privileged: true
          seLinuxOptions:
            level: "s0"
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/containerd/
          name: containerd-conf
        - mountPath: /run/containerd/containerd.sock
          name: containerd-socket
        - mountPath: /opt/nvidia-gpu-operator/artifacts/runtimeclasses/
          name: runtimeclass-artifacts
        - name: kata-manager-conf
          mountPath: "/etc/kubernetes/kata-manager/"
          readOnly: true
        - name: host-root
          mountPath: "/host"
          readOnly: true
          mountPropagation: HostToContainer
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kata-manager-conf
        configMap:
          name: kata-manager-conf
      - hostPath:
          path: /etc/containerd/
          type: ""
        name: containerd-conf
      - hostPath:
          path: /run/containerd/containerd.sock
          type: ""
        name: containerd-socket
      - hostPath:
          path: /opt/nvidia-gpu-operator/artifacts/runtimeclasses/
          type: DirectoryOrCreate
        name: runtimeclass-artifacts
      - hostPath:
          path: /
        name: host-root
